# Configuration options are documented at:
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
sudo: false
language: node_js
node_js:
  - '18'
  - '20'
  - '21'
script: npm test
after_success: npm run coverage
