# Configuration options are documented at:
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
sudo: false
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '9'
script: npm test
after_script: npm run report-coverage
