# Configuration options are documented at:
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
sudo: false
language: node_js
node_js:
  - '4'
  - '5'
# Only report coverage on Node.js 4 or later.
after_script: ./bin/node-has-es6 && npm run report-coverage
