docs:
	echo && echo "Building JavaScript documentation with jsdoc…" && echo
	rm -r ./gh-pages/fonts ./gh-pages/scripts ./gh-pages/styles ./gh-pages/*.html
	./node_modules/.bin/jsdoc --configure ./gh-pages/api-jsdoc-conf.json
	echo
	# Clean up the JS docs.
	for HTMLDOC in ./gh-pages/**.html; do cat $$HTMLDOC | sed 's/<title>JSDoc: /<title>sassy-test JavaScript API: /' | sed -E 's/(Documentation generated by .+<\/a>).+/\1/' > $$HTMLDOC.tmp; mv $$HTMLDOC.tmp $$HTMLDOC; done

.PHONY: docs
